{% set name = "cdsapi" %}
{% set version = "0.2.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #url: https://files.pythonhosted.org/packages/2d/f0/40c8f2f36e2176bbce5557fc2a9bb570f807028968fdad6f4586a0656450/cdsapi-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/4e/d7/8a0abd3e63c40ad2d7c6eac5fc4bdf13fa72e96a36688822a2fb0ca0814b/cdsapi-0.2.7.tar.gz
  sha256: 3697d1a473c9d78540d25b4b905a4103a109d54595a0cdb0c35308166cc12d20

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - requests
    - tqdm
  run:
    - python
    - requests
    - tqdm

test:
  imports:
    - cdsapi


about:
  home: https://software.ecmwf.int/stash/projects/CDS/repos/cdsapi
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'API to access the Copernicus Climate Data Store at ECMWF'

  doc_url: https://cds.climate.copernicus.eu/api-how-to
  dev_url: https://github.com/ecmwf/cdsapi 

extra:
  recipe-maintainers:
    - StephanSiemen
