{% set name = "cdsapi" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdsapi-{{ version }}.tar.gz
  sha256: 19f3e92f1996cc1115d0b0281617edeaecf3eefca03fbd384cfbc520d5f0476d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests >=2.5.0
    - tqdm

test:
  imports:
    - cdsapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://software.ecmwf.int/stash/projects/CDS/repos/cdsapi
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: API to access the Copernicus Climate Data Store at ECMWF

  doc_url: https://cds.climate.copernicus.eu/api-how-to
  dev_url: https://github.com/ecmwf/cdsapi

extra:
  recipe-maintainers:
    - StephanSiemen
    - akrherz
    - ocefpaf
