{% set name = "cdsapi" %}
{% set version = "0.7.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cdsapi-{{ version }}.tar.gz
  sha256: a32fedb6cf6c5683e488652fadbf5b956561f573e98d0ec474e2d8381fe24a34

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - cads-api-client >=1.4.7
    - requests >=2.5.0
    - tqdm

test:
  imports:
    - cdsapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://software.ecmwf.int/stash/projects/CDS/repos/cdsapi
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: API to access the Copernicus Climate Data Store at ECMWF

  doc_url: https://cds.climate.copernicus.eu/api-how-to
  dev_url: https://github.com/ecmwf/cdsapi

extra:
  recipe-maintainers:
    - StephanSiemen
    - akrherz
    - ocefpaf
