travis:
  secure:
    BINSTAR_TOKEN: XnOriNP6bjx7gSpWl7bNA950/7HFkLaiDnEUC9wS2BhGlXgRdDXtLdTkJeHDYbWyDMhFZRJsyw8X/2DPAPAPt5WRSVBWxPoQECWQ/WDr4VHrhqPwmaMBBfzQPTXa/lXDcYl8WGLLEJpB1E3L0yjrQFmMD+7j5TdtpzXWQ1Q5OzjbYl+zqVdZWD+qhSedf0z3wEwRBdbhBzwbqnsvirllP2IC/5msahxYZIXv+NOzF7Tqwp5KhT1gTKl9Yzc1AJLfqKou24WAcHs7rkkPK97uENO+VXXig6AP2OsZPUtcCR5/OCYNk8jGGL6S1h3dixVzHEpkW7/qAKtxMu1N/pc+v/FiS24MMYhAznm2utd6SdWNo6t/Jv+SwnAB5v8MfpIBKrXK8dAtM5Z+zhYjy5EysS77o3UkjEM5l4uhBuu+kvpkIpYQaHld4Zp+ZLHb+4az2jLQPdPUEI+a1emUcIDhGVgwbHMqf1FhWVPqz5Aqh5mJFeknh1M7zswsfJ+qL8hFXxIsepWHVMMMcBD7Jti37XSzspa/UwJP9UvVA6bX08qLvjXGMYjxrvgm8Tr5te5ZzZTkuDQsq945DS1E0erXjEF1jlIYSh5IXaZKgHCxmqYqWdZAJ1egzfh3a+uoQ2XS/jjA0RcGBVyzXJjd6J5OFHN3STvbc5O1aLvTa0UuFgI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
